// Eine kuratierte Auswahl wichtiger Sehenswürdigkeiten in Japan mit passenden Emojis und Koordinaten
// Struktur: { name, city, type, emoji, lat, lng, desc }
const attractions = [
  // Hokkaido
  { name: "Sapporo Schneefestival (Odori-Park)", city: "Sapporo", type: "Festival", emoji: "❄️", lat: 43.0621, lng: 141.3544, desc: "Eisskulpturen und Winterstimmung im Stadtzentrum." },
  { name: "Otaru-Kanal", city: "Otaru", type: "Kanal/Viertel", emoji: "🚤", lat: 43.1976, lng: 140.9947, desc: "Historischer Kanal mit romantischer Uferpromenade." },
  { name: "Furano & Biei Blumenfelder", city: "Furano/Biei", type: "Natur", emoji: "🌻", lat: 43.3423, lng: 142.3830, desc: "Leuchtende Blumenfelder und sanfte Hügel." },
  { name: "Daisetsuzan Nationalpark", city: "Hokkaido", type: "Nationalpark", emoji: "🏞️", lat: 43.6580, lng: 142.8540, desc: "Größter Nationalpark Japans, wilde Berglandschaften." },
  { name: "Shiretoko-Halbinsel", city: "Shari", type: "UNESCO/Nationalpark", emoji: "🏞️", lat: 44.1230, lng: 145.1250, desc: "Unberührte Natur, Bären und Küstenklippen." },
  { name: "Lake Akan & Ainu-Kotan", city: "Kushiro", type: "See/Kultur", emoji: "🛶", lat: 43.4480, lng: 144.1030, desc: "Klarer Kratersee und Ainu-Kultur." },
  { name: "Noboribetsu Onsen (Jigokudani)", city: "Noboribetsu", type: "Onsen", emoji: "♨️", lat: 42.4920, lng: 141.1440, desc: "Dampfende Höllentäler und Thermalbäder." },
  { name: "Asahiyama Zoo", city: "Asahikawa", type: "Zoo", emoji: "🐧", lat: 43.7687, lng: 142.4823, desc: "Beliebter Zoo mit naturnahen Gehegen." },
  { name: "Kap Kamui (Shakotan)", city: "Shakotan", type: "Kap/Küste", emoji: "🌊", lat: 43.3097, lng: 140.4852, desc: "Türkises Meer und dramatische Klippen." },

  // Tohoku
  { name: "Matsushima-Bucht", city: "Miyagi", type: "Bucht", emoji: "🌊", lat: 38.3704, lng: 141.0614, desc: "Eine der drei schönsten Landschaften Japans." },
  { name: "Hirosaki-jo (Burg) & Park", city: "Hirosaki", type: "Burg/Kirschblüte", emoji: "🏯", lat: 40.6065, lng: 140.4635, desc: "Kirschblüte vor historischer Burgkulisse." },
  { name: "Towada-See", city: "Aomori/Akita", type: "See", emoji: "🏞️", lat: 40.4500, lng: 140.8940, desc: "Tiefer Kratersee in waldiger Umgebung." },
  { name: "Oirase-Schlucht", city: "Aomori", type: "Schlucht", emoji: "🏞️", lat: 40.4860, lng: 140.9500, desc: "Moosige Ufer, klare Bäche und Wasserfälle." },
  { name: "Yamadera (Risshaku-ji)", city: "Yamagata", type: "Tempel", emoji: "🛕", lat: 38.3103, lng: 140.4322, desc: "Bergtempel mit 1000 Stufen und Weitblick." },
  { name: "Ginzan Onsen", city: "Obanazawa", type: "Onsen", emoji: "♨️", lat: 38.5580, lng: 140.5140, desc: "Taisho-Romantik und gasbeleuchtete Gassen." },
  { name: "Zao Onsen & Schneemonster", city: "Yamagata", type: "Onsen/Winter", emoji: "♨️", lat: 38.1700, lng: 140.4100, desc: "Skiresort mit bizarren vereisten Bäumen." },
  { name: "Tazawa-See", city: "Semboku", type: "See", emoji: "🏞️", lat: 39.7310, lng: 140.7300, desc: "Tiefster See Japans mit türkisblauem Wasser." },
  { name: "Kakunodate Samurai-Viertel", city: "Semboku", type: "Altstadt", emoji: "🏘️", lat: 39.5930, lng: 140.5640, desc: "Gut erhaltene Samurai-Residenzen." },
  { name: "Aizu-Wakamatsu (Tsuruga-jo)", city: "Fukushima", type: "Burg", emoji: "🏯", lat: 37.4940, lng: 139.9290, desc: "Weiße Burg mit Geschichte des Boshin-Kriegs." },
  { name: "Sendai Zuihoden", city: "Sendai", type: "Mausoleum", emoji: "🏛️", lat: 38.2460, lng: 140.8660, desc: "Prächtiges Mausoleum von Date Masamune." },
  { name: "Aomori Nebuta Museum WA-RASSE", city: "Aomori", type: "Festival/Museum", emoji: "🎆", lat: 40.8280, lng: 140.7340, desc: "Leuchtende Festwagen der Nebuta-Matsuri." },
  { name: "Tashirojima (Katzeninsel)", city: "Ishinomaki (Miyagi)", type: "Insel/Katzen", emoji: "🐈", lat: 38.2969, lng: 141.3919, desc: "Kleine Insel mit frei laufenden Katzen; Fähre ab Ishinomaki." },

  // Kanto (Tokio & Umgebung)
  { name: "Senso-ji (Asakusa)", city: "Tokyo", type: "Tempel", emoji: "🛕", lat: 35.7148, lng: 139.7967, desc: "Tokyos ältester Tempel mit Kaminari-mon." },
  { name: "Meiji Jingu", city: "Tokyo", type: "Schrein", emoji: "⛩️", lat: 35.6764, lng: 139.6993, desc: "Waldschrein nahe Harajuku/Shibuya." },
  { name: "Shibuya Crossing", city: "Tokyo", type: "Kreuzung", emoji: "🚦", lat: 35.6595, lng: 139.7005, desc: "Legendäre Kreuzung mit Menschenströmen." },
  { name: "Tokyo Skytree", city: "Tokyo", type: "Turm", emoji: "🗼", lat: 35.7101, lng: 139.8107, desc: "Aussichts- und Fernsehturm mit Solamachi." },
  { name: "Tokyo Tower", city: "Tokyo", type: "Turm", emoji: "🗼", lat: 35.6586, lng: 139.7454, desc: "Ikone im Herzen Tokyos." },
  { name: "Akihabara", city: "Tokyo", type: "Elektronik/Popkultur", emoji: "🎮", lat: 35.6984, lng: 139.7730, desc: "Otaku-, Games- und Elektronik-Mekka." },
  { name: "teamLab Planets", city: "Tokyo (Toyosu)", type: "Museum", emoji: "🏛️", lat: 35.6457, lng: 139.7969, desc: "Immersive Licht- und Wasserinstallationen." },
  { name: "Ueno-Park & Museen", city: "Tokyo", type: "Park/Museen", emoji: "🌳", lat: 35.7156, lng: 139.7730, desc: "Großer Park mit Zoo und Top-Museen." },
  { name: "Shinjuku Gyoen", city: "Tokyo", type: "Garten/Park", emoji: "🌳", lat: 35.6852, lng: 139.7100, desc: "Oase mit japanischem, englischem und franz. Garten." },
  { name: "Tsukiji Outer Market", city: "Tokyo", type: "Markt/Essen", emoji: "🍣", lat: 35.6655, lng: 139.7700, desc: "Streetfood und frische Meeresfrüchte." },
  { name: "Ghibli Museum", city: "Mitaka (Tokyo)", type: "Museum", emoji: "🏛️", lat: 35.7023, lng: 139.5703, desc: "Zauberhaftes Museum für Studio Ghibli." },
  { name: "Yokohama Minato Mirai", city: "Yokohama", type: "Stadtbild", emoji: "🌆", lat: 35.4570, lng: 139.6380, desc: "Uferpromenade mit Landmark Tower." },
  { name: "Yokohama Chinatown", city: "Yokohama", type: "Viertel/Essen", emoji: "🍜", lat: 35.4420, lng: 139.6500, desc: "Größtes Chinatown Japans." },
  { name: "Cup Noodles Museum", city: "Yokohama", type: "Museum", emoji: "🏛️", lat: 35.4550, lng: 139.6380, desc: "Instantnudel-Geschichte zum Mitmachen." },
  { name: "Großer Buddha von Kamakura", city: "Kamakura", type: "Tempel/Buddha", emoji: "🛕", lat: 35.3167, lng: 139.5350, desc: "Daibutsu im Kotoku-in." },
  { name: "Tsurugaoka Hachimangu", city: "Kamakura", type: "Schrein", emoji: "⛩️", lat: 35.3260, lng: 139.5540, desc: "Wichtigster Schrein Kamakuras." },
  { name: "Enoshima", city: "Fujisawa", type: "Insel/Strand", emoji: "🏝️", lat: 35.3000, lng: 139.4800, desc: "Freizeitinsel mit Leuchtturm und Stränden." },
  { name: "Nikko Toshogu", city: "Nikko", type: "Schrein", emoji: "⛩️", lat: 36.7570, lng: 139.5993, desc: "Prächtig verzierter Schrein (UNESCO)." },
  { name: "Kegon-Wasserfall", city: "Nikko", type: "Wasserfall", emoji: "💧", lat: 36.7350, lng: 139.4930, desc: "Spektakulärer Fall am Chuzenji-See." },
  { name: "Chuzenji-See", city: "Nikko", type: "See", emoji: "🏞️", lat: 36.7450, lng: 139.5110, desc: "Hochgelegener See westlich von Nikko." },
  { name: "Hakone Ashi-See", city: "Hakone", type: "See", emoji: "🏞️", lat: 35.2040, lng: 139.0240, desc: "Postkartenblick mit Torii und Fuji." },
  { name: "Owakudani", city: "Hakone", type: "Vulkanlandschaft", emoji: "🌋", lat: 35.2420, lng: 139.0190, desc: "Schwefeldämpfe, schwarze Eier und Ausblicke." },
  { name: "Hakone Open-Air Museum", city: "Hakone", type: "Museum", emoji: "🏛️", lat: 35.2560, lng: 139.1040, desc: "Skulpturenpark inmitten der Berge." },
  { name: "Kawagoe (Little Edo)", city: "Kawagoe", type: "Altstadt", emoji: "🏘️", lat: 35.9250, lng: 139.4850, desc: "Glockenturm Toki no Kane und Altstadtgassen." },
  { name: "Chureito-Pagode (Arakura Sengen)", city: "Fujiyoshida", type: "Schrein/Pagode", emoji: "⛩️", lat: 35.4930, lng: 138.8090, desc: "Fuji-Blick mit roter Pagode (Sakura)." },

  // Chubu (Zentraljapan)
  { name: "Fuji-san (Mount Fuji)", city: "Shizuoka/Yamanashi", type: "Berg", emoji: "🗻", lat: 35.3606, lng: 138.7274, desc: "Ikonischer Vulkan und UNESCO-Welterbe." },
  { name: "Jigokudani Schneeaffen-Park", city: "Yamanouchi", type: "Tiere/Onsen", emoji: "🐒", lat: 36.7320, lng: 138.4620, desc: "Badenende Makaken im Winterdampf." },
  { name: "Matsumoto-jo (Burg)", city: "Matsumoto", type: "Burg", emoji: "🏯", lat: 36.2380, lng: 137.9690, desc: "Schwarze Burg, auch " + "Krähenburg" + "." },
  { name: "Zenko-ji", city: "Nagano", type: "Tempel", emoji: "🛕", lat: 36.6610, lng: 138.1870, desc: "Einer der ältesten Tempel Japans." },
  { name: "Takayama Altstadt", city: "Takayama", type: "Altstadt", emoji: "🏘️", lat: 36.1400, lng: 137.2560, desc: "Sake-Brauereien und traditionelle Häuser." },
  { name: "Shirakawa-go (Gassho-Zukuri)", city: "Gifu", type: "UNESCO/Dorf", emoji: "🏘️", lat: 36.2600, lng: 136.8980, desc: "Strohdachhöfe in Bergtälern." },
  { name: "Kenrokuen-Garten", city: "Kanazawa", type: "Garten", emoji: "🏛️", lat: 36.5610, lng: 136.6620, desc: "Einer der drei berühmten Gärten Japans." },
  { name: "Burg Kanazawa", city: "Kanazawa", type: "Burg", emoji: "🏯", lat: 36.5660, lng: 136.6590, desc: "Weitläufige Burganlage am Kenrokuen." },
  { name: "Higashi Chaya-Gasse", city: "Kanazawa", type: "Altstadt", emoji: "🏘️", lat: 36.5730, lng: 136.6730, desc: "Teehäuser und Geisha-Tradition." },
  { name: "Tateyama-Kurobe (Murodo)", city: "Toyama", type: "Bergroute", emoji: "🏞️", lat: 36.5750, lng: 137.6030, desc: "Schneehochstraße und Alpenpanoramen." },
  { name: "Kurobe-Staudamm", city: "Toyama", type: "Staudamm", emoji: "🏞️", lat: 36.5600, lng: 137.6690, desc: "Imposanter Bogenstaudamm in den Alpen." },
  { name: "Nakasendo Magome", city: "Gifu", type: "Wanderweg", emoji: "🥾", lat: 35.5160, lng: 137.6070, desc: "Poststation auf der historischen Nakasendo." },
  { name: "Nakasendo Tsumago", city: "Nagano", type: "Wanderweg", emoji: "🥾", lat: 35.4650, lng: 137.5970, desc: "Authentisches Edo-Postdorf." },
  { name: "Izu Jogasaki-Küste", city: "Ito (Shizuoka)", type: "Küste", emoji: "🌊", lat: 34.8770, lng: 139.1100, desc: "Klippenpfade, Hängebrücke und Brandung." },
  { name: "Atami Onsen", city: "Atami", type: "Onsen", emoji: "♨️", lat: 35.0960, lng: 139.0770, desc: "Küsten-Onsen nahe Tokio." },
  { name: "Nagoya-jo (Burg)", city: "Nagoya", type: "Burg", emoji: "🏯", lat: 35.1850, lng: 136.8990, desc: "Berühmt für goldene Shachihoko." },
  { name: "Osu Shopping District", city: "Nagoya", type: "Viertel/Essen", emoji: "🍜", lat: 35.1580, lng: 136.9060, desc: "Streetfood, Tempel und Secondhand." },
  { name: "Ghibli Park", city: "Nagakute (Aichi)", type: "Freizeitpark", emoji: "🎢", lat: 35.1730, lng: 137.1240, desc: "Themenbereiche rund um Studio Ghibli." },
  { name: "Ise-jingu", city: "Ise (Mie)", type: "Schrein", emoji: "⛩️", lat: 34.4550, lng: 136.7250, desc: "Heiligster Schrein des Shinto." },

  // Kansai
  { name: "Fushimi Inari-taisha", city: "Kyoto", type: "Schrein", emoji: "⛩️", lat: 34.9671, lng: 135.7727, desc: "Tausende rote Torii-Tore am Berghang." },
  { name: "Kiyomizu-dera", city: "Kyoto", type: "Tempel", emoji: "🛕", lat: 34.9949, lng: 135.7850, desc: "Holztempel mit Aussichtsbühne." },
  { name: "Kinkaku-ji (Goldener Pavillon)", city: "Kyoto", type: "Tempel", emoji: "🛕", lat: 35.0394, lng: 135.7292, desc: "Goldglänzender Pavillon am Teich." },
  { name: "Ginkaku-ji (Silberner Pavillon)", city: "Kyoto", type: "Tempel", emoji: "🛕", lat: 35.0270, lng: 135.7986, desc: "Zen-Tempel mit Steingarten." },
  { name: "Arashiyama Bambuswald", city: "Kyoto", type: "Natur", emoji: "🎋", lat: 35.0094, lng: 135.6668, desc: "Atmosphärischer Bambuswald." },
  { name: "Nijo-jo (Burg Nijo)", city: "Kyoto", type: "Burg", emoji: "🏯", lat: 35.0140, lng: 135.7480, desc: "Shogun-Residenz mit Nachtigallenböden." },
  { name: "Philosophenweg", city: "Kyoto", type: "Spazierweg", emoji: "🌸", lat: 35.0260, lng: 135.7980, desc: "Kirschblütenweg entlang eines Kanals." },
  { name: "Nishiki-Markt", city: "Kyoto", type: "Markt/Essen", emoji: "🍜", lat: 35.0050, lng: 135.7640, desc: "Kyotos Küche unter einem Dach." },
  { name: "Nara-Park & Todai-ji", city: "Nara", type: "Park/Tempel", emoji: "🦌", lat: 34.6851, lng: 135.8431, desc: "Freilaufende Hirsche und große Buddha-Halle." },
  { name: "Kasuga Taisha", city: "Nara", type: "Schrein", emoji: "⛩️", lat: 34.6810, lng: 135.8480, desc: "Stein- und Bronzelaternen im Wald." },
  { name: "Dotonbori", city: "Osaka", type: "Viertel/Essen", emoji: "🍜", lat: 34.6687, lng: 135.5011, desc: "Neon, Streetfood und Glico-Mann." },
  { name: "Osaka-jo (Burg)", city: "Osaka", type: "Burg", emoji: "🏯", lat: 34.6873, lng: 135.5262, desc: "Burgpark und Museum." },
  { name: "Umeda Sky Building", city: "Osaka", type: "Aussicht", emoji: "🌆", lat: 34.7055, lng: 135.4892, desc: "Schwebende Gartenplattform mit Blick." },
  { name: "Shinsekai", city: "Osaka", type: "Viertel", emoji: "🌃", lat: 34.6525, lng: 135.5063, desc: "Retro-Charme rund um Tsutenkaku." },
  { name: "Kaiyukan Aquarium", city: "Osaka", type: "Aquarium", emoji: "🐠", lat: 34.6545, lng: 135.4283, desc: "Eines der größten Aquarien der Welt." },
  { name: "Universal Studios Japan", city: "Osaka", type: "Freizeitpark", emoji: "🎢", lat: 34.6654, lng: 135.4323, desc: "Themenwelten von Nintendo bis Harry Potter." },
  { name: "Himeji-jo (Burg Himeji)", city: "Himeji", type: "Burg", emoji: "🏯", lat: 34.8394, lng: 134.6939, desc: "Prächtige weiße Burg (UNESCO)." },
  { name: "Koyasan & Okunoin", city: "Wakayama", type: "Tempel/Friedhof", emoji: "🛕", lat: 34.2128, lng: 135.5860, desc: "Spirituelles Zentrum des Shingon-Buddhismus." },
  { name: "Kumano Nachi no Taki", city: "Nachikatsuura", type: "Wasserfall", emoji: "💧", lat: 33.6670, lng: 135.8890, desc: "Hoher Wasserfall neben Schrein." },
  { name: "Kinosaki Onsen", city: "Toyooka", type: "Onsen", emoji: "♨️", lat: 35.6260, lng: 134.8130, desc: "Badepass durch sieben Badehäuser." },
  { name: "Amanohashidate", city: "Miyazu", type: "Sandbank/Panorama", emoji: "🌊", lat: 35.5660, lng: 135.1950, desc: "Himmelspfad über der Bucht." },

  // Chugoku
  { name: "Friedensdenkmal Hiroshima", city: "Hiroshima", type: "Memorial", emoji: "🕊️", lat: 34.3955, lng: 132.4536, desc: "Gedenkstätte und Museum." },
  { name: "Itsukushima-Schrein (Miyajima)", city: "Hatsukaichi", type: "Schrein", emoji: "⛩️", lat: 34.2956, lng: 132.3199, desc: "Schwimmendes Torii im Meer." },
  { name: "Korakuen-Garten", city: "Okayama", type: "Garten", emoji: "🏛️", lat: 34.6693, lng: 133.9344, desc: "Weitläufiger Daimyo-Garten." },
  { name: "Burg Okayama", city: "Okayama", type: "Burg", emoji: "🏯", lat: 34.6654, lng: 133.9350, desc: "Schwarze Burg am Asahi-Fluss." },
  { name: "Kurashiki Bikan Altstadt", city: "Kurashiki", type: "Altstadt", emoji: "🏘️", lat: 34.5958, lng: 133.7718, desc: "Weißverputzte Lagerhäuser entlang des Kanals." },
  { name: "Tottori Sanddünen", city: "Tottori", type: "Dünen", emoji: "🏜️", lat: 35.5403, lng: 134.2383, desc: "Wüstenhafte Landschaft am Meer." },
  { name: "Izumo Taisha", city: "Izumo", type: "Schrein", emoji: "⛩️", lat: 35.4010, lng: 132.6853, desc: "Einer der ältesten Schreine Japans." },
  { name: "Adachi Museum of Art", city: "Yasugi", type: "Museum/Garten", emoji: "🏛️", lat: 35.4314, lng: 133.2508, desc: "Berühmter Museumsgarten." },
  { name: "Kintaikyo-Brücke", city: "Iwakuni", type: "Brücke", emoji: "🌉", lat: 34.1667, lng: 132.1789, desc: "Fünfbögige Holzbrücke über den Nishiki." },
  { name: "Sandankyo-Schlucht", city: "Hiroshima", type: "Schlucht", emoji: "🏞️", lat: 34.5670, lng: 132.2530, desc: "Bootstouren und Wasserfälle in enger Schlucht." },

  // Shikoku
  { name: "Ritsurin-Garten", city: "Takamatsu", type: "Garten", emoji: "🏛️", lat: 34.3302, lng: 134.0434, desc: "Weitläufiger Garten mit Teichen und Hügeln." },
  { name: "Dogo Onsen", city: "Matsuyama", type: "Onsen", emoji: "♨️", lat: 33.8502, lng: 132.7799, desc: "Eines der ältesten Badehäuser Japans." },
  { name: "Matsuyama-jo (Burg)", city: "Matsuyama", type: "Burg", emoji: "🏯", lat: 33.8456, lng: 132.7656, desc: "Burg auf einem Hügel mit Blick über die Stadt." },
  { name: "Iya-Tal & Rebenbrücken", city: "Miyoshi", type: "Tal/Brücke", emoji: "🌉", lat: 33.9030, lng: 133.8140, desc: "Abgelegene Schluchten und historische Hängebrücken." },
  { name: "Kochi-jo (Burg)", city: "Kochi", type: "Burg", emoji: "🏯", lat: 33.5597, lng: 133.5311, desc: "Eine der wenigen originalen Burgen Japans." },
  { name: "Naruto-Strudel", city: "Naruto", type: "Meeresstrudel", emoji: "🌊", lat: 34.1708, lng: 134.6412, desc: "Spektakuläre Gezeitenstrudel in der Meerenge." },
  { name: "Shikoku 88-Tempel-Pilgerweg (Ryozenji)", city: "Tokushima", type: "Pilgerweg", emoji: "🥾", lat: 34.1308, lng: 134.5119, desc: "Starttempel des Henro-Pilgerwegs." },
  { name: "Aoshima (Katzeninsel)", city: "Ozu (Ehime)", type: "Insel/Katzen", emoji: "🐈", lat: 33.5011, lng: 132.2374, desc: "Berühmte Katzeninsel im Seto-Binnenmeer." },

  // Kyushu
  { name: "Ohori-Park", city: "Fukuoka", type: "Park", emoji: "🌳", lat: 33.5869, lng: 130.3763, desc: "Zentraler Seepark mit Laufstrecken." },
  { name: "Dazaifu Tenmangu", city: "Dazaifu", type: "Schrein", emoji: "⛩️", lat: 33.5222, lng: 130.5341, desc: "Bildungs-Schrein mit Pflaumenblüte." },
  { name: "Ainoshima (Katzeninsel)", city: "Shingu (Fukuoka)", type: "Insel/Katzen", emoji: "🐈", lat: 33.7440, lng: 130.3220, desc: "Katzenreiche Insel bei Fukuoka; Fähre ab Shingu." },
  { name: "Nagasaki Friedenspark", city: "Nagasaki", type: "Memorial", emoji: "🕊️", lat: 32.7766, lng: 129.8647, desc: "Gedenkpark nahe dem Hypozentrum." },
  { name: "Glover Garden", city: "Nagasaki", type: "Garten", emoji: "🏛️", lat: 32.7357, lng: 129.8694, desc: "Historische westliche Residenzen." },
  { name: "Hashima (Gunkanjima)", city: "Nagasaki", type: "Insel/Industrie", emoji: "🏝️", lat: 32.6278, lng: 129.7386, desc: "Verlassene Kohleinsel, Bootsfahrten ab Nagasaki." },
  { name: "Kumamoto-jo (Burg)", city: "Kumamoto", type: "Burg", emoji: "🏯", lat: 32.8031, lng: 130.7079, desc: "Mächtige Burg, teils restauriert." },
  { name: "Suizenji Jojuen", city: "Kumamoto", type: "Garten", emoji: "🏛️", lat: 32.7878, lng: 130.7412, desc: "Miniaturlandschaften und Teehäuser." },
  { name: "Aso-Kaldera", city: "Aso", type: "Vulkan", emoji: "🌋", lat: 32.8840, lng: 131.1040, desc: "Eine der größten Vulkan-Calderen der Welt." },
  { name: "Beppu Jigoku (Höllen)", city: "Beppu", type: "Onsen", emoji: "♨️", lat: 33.3074, lng: 131.4915, desc: "Farbige Thermalquellen und Fußbäder." },
  { name: "Yufuin", city: "Yufu", type: "Onsen", emoji: "♨️", lat: 33.2617, lng: 131.3195, desc: "Gemütlicher Kurort mit Kunst und Natur." },
  { name: "Takachiho-Schlucht", city: "Miyazaki", type: "Schlucht", emoji: "🏞️", lat: 32.7036, lng: 131.3086, desc: "Basaltschlucht mit Booten und Wasserfällen." },
  { name: "Kagoshima & Sakurajima", city: "Kagoshima", type: "Vulkan", emoji: "🌋", lat: 31.5934, lng: 130.6628, desc: "Aktiver Vulkan in der Bucht von Kagoshima." },
  { name: "Yakushima", city: "Yakushima", type: "UNESCO/Natur", emoji: "🌳", lat: 30.3580, lng: 130.5280, desc: "Urige Zedernwälder und moosige Pfade." },

  // Okinawa
  { name: "Shuri-jo (Schloss Shuri)", city: "Naha", type: "Schloss", emoji: "🏯", lat: 26.2174, lng: 127.7195, desc: "Wiederaufbau des Ryukyu-Palastkomplexes." },
  { name: "Churaumi-Aquarium", city: "Motobu", type: "Aquarium", emoji: "🐠", lat: 26.6942, lng: 127.8779, desc: "Walhaie und riesige Becken." },
  { name: "Cape Manzamo", city: "Onna", type: "Kap/Küste", emoji: "🌊", lat: 26.5027, lng: 127.8522, desc: "Elefantenrüssel-Klippe über türkisfarbenem Meer." },
  { name: "Kouri-Brücke", city: "Nakijin", type: "Brücke", emoji: "🌉", lat: 26.7108, lng: 127.9640, desc: "Lange Meeresbrücke mit Traumfarben." },
  { name: "Kerama-Inseln (Zamami)", city: "Zamami", type: "Insel/Meer", emoji: "🏝️", lat: 26.2300, lng: 127.3040, desc: "Schnorchelparadies nahe Naha." },
  { name: "Miyakojima (Yonaha Maehama)", city: "Miyako", type: "Strand", emoji: "🏖️", lat: 24.7370, lng: 125.3110, desc: "Pulverstrand und türkisfarbenes Wasser." },
  { name: "Kabira-Bucht (Ishigaki)", city: "Ishigaki", type: "Bucht", emoji: "🌊", lat: 24.4723, lng: 124.1359, desc: "Postkartenbucht mit smaragdgrünem Wasser." },
  { name: "Iriomote (Mangroven & Wasserfälle)", city: "Iriomote", type: "Natur", emoji: "🛶", lat: 24.3500, lng: 123.8830, desc: "Dschungel, Mangroven und Flussabenteuer." }
];
