// Mapping: Attraktionsname -> Externer Link (Wikipedia/Offiziell)
// Hinweis: Die Schlüssel müssen exakt mit dem Feld `name` in attractions.js übereinstimmen.
// Sie können diese Liste beliebig erweitern.
window.attractionLinks = {
  // Hokkaido
  "Sapporo Schneefestival (Odori-Park)": "https://de.wikipedia.org/wiki/Sapporo-Schneefestival",
  "Otaru-Kanal": "https://de.wikipedia.org/wiki/Otaru",
  "Furano & Biei Blumenfelder": "https://en.visit-hokkaido.jp/destinations/furano-biei/",
  "Daisetsuzan Nationalpark": "https://de.wikipedia.org/wiki/Daisetsuzan-Nationalpark",
  "Shiretoko-Halbinsel": "https://de.wikipedia.org/wiki/Shiretoko-Halbinsel",
  "Lake Akan & Ainu-Kotan": "https://en.wikipedia.org/wiki/Lake_Akan",
  "Noboribetsu Onsen (Jigokudani)": "https://noboribetsu-spa.jp/en/",
  "Asahiyama Zoo": "https://www.city.asahikawa.hokkaido.jp/asahiyamazoo/",
  "Kap Kamui (Shakotan)": "https://en.wikipedia.org/wiki/Cape_Kamui",

  // Tohoku
  "Matsushima-Bucht": "https://de.wikipedia.org/wiki/Matsushima",
  "Hirosaki-jo (Burg) & Park": "https://de.wikipedia.org/wiki/Burg_Hirosaki",
  "Towada-See": "https://de.wikipedia.org/wiki/Towada-See",
  "Oirase-Schlucht": "https://de.wikipedia.org/wiki/Oirase",
  "Yamadera (Risshaku-ji)": "https://de.wikipedia.org/wiki/Risshaku-ji",
  "Ginzan Onsen": "https://www.google.com/search?q=Ginzan%20Onsen",
  "Zao Onsen & Schneemonster": "https://en.wikipedia.org/wiki/Mount_Zao",
  "Tazawa-See": "https://de.wikipedia.org/wiki/Tazawa-See",
  "Kakunodate Samurai-Viertel": "https://en.wikipedia.org/wiki/Kakunodate",
  "Aizu-Wakamatsu (Tsuruga-jo)": "https://de.wikipedia.org/wiki/Burg_Aizu-Wakamatsu",
  "Sendai Zuihoden": "https://www.zuihoden.com/english/",
  "Aomori Nebuta Museum WA-RASSE": "https://www.nebuta.jp/warasse/english/",
  "Tashirojima (Katzeninsel)": "https://en.wikipedia.org/wiki/Tashirojima",

  // Kanto (Tokio & Umgebung)
  "Senso-ji (Asakusa)": "https://de.wikipedia.org/wiki/Sens%C5%8D-ji",
  "Meiji Jingu": "https://de.wikipedia.org/wiki/Meiji-Schrein",
  "Shibuya Crossing": "https://en.wikipedia.org/wiki/Shibuya_Crossing",
  "Tokyo Skytree": "https://www.google.com/search?q=Tokyo%20Skytree",
  "Tokyo Tower": "https://de.wikipedia.org/wiki/Tokio_Tower",
  "Akihabara": "https://de.wikipedia.org/wiki/Akihabara",
  "teamLab Planets": "https://planets.teamlab.art/tokyo/",
  "Ueno-Park & Museen": "https://de.wikipedia.org/wiki/Ueno-Park",
  "Shinjuku Gyoen": "https://de.wikipedia.org/wiki/Shinjuku_Gyoen",
  "Tsukiji Outer Market": "https://www.tsukiji.or.jp/english/",
  "Ghibli Museum": "https://www.ghibli-museum.jp/en/",
  "Yokohama Minato Mirai": "https://en.wikipedia.org/wiki/Minato_Mirai_21",
  "Yokohama Chinatown": "https://en.wikipedia.org/wiki/Yokohama_Chinatown",
  "Cup Noodles Museum": "https://www.cupnoodles-museum.jp/en/yokohama/",
  "Großer Buddha von Kamakura": "https://www.google.com/search?q=Gro%C3%9Fer%20Buddha%20von%20Kamakura",
  "Tsurugaoka Hachimangu": "https://de.wikipedia.org/wiki/Tsurugaoka_Hachiman-g%C5%ū",
  "Enoshima": "https://en.wikipedia.org/wiki/Enoshima",
  "Nikko Toshogu": "https://de.wikipedia.org/wiki/T%C5%8Dsh%C5%8D-g%C5%ū",
  "Kegon-Wasserfall": "https://www.google.com/search?q=Kegon-Wasserfall",
  "Chuzenji-See": "https://de.wikipedia.org/wiki/Ch%C5%ūzenji-See",
  "Hakone Ashi-See": "https://de.wikipedia.org/wiki/Ashi-See",
  "Owakudani": "https://en.wikipedia.org/wiki/%C5%8Cwakudani",
  "Hakone Open-Air Museum": "https://www.hakone-oam.or.jp/en/",
  "Kawagoe (Little Edo)": "https://en.wikipedia.org/wiki/Kawagoe,_Saitama",
  "Chureito-Pagode (Arakura Sengen)": "https://en.wikipedia.org/wiki/Arakurayama_Sengen_Park",

  // Chubu (Zentraljapan)
  "Fuji-san (Mount Fuji)": "https://de.wikipedia.org/wiki/Fuji",
  "Jigokudani Schneeaffen-Park": "https://en.jigokudani-yaenkoen.co.jp/",
  "Matsumoto-jo (Burg)": "https://de.wikipedia.org/wiki/Burg_Matsumoto",
  "Zenko-ji": "https://de.wikipedia.org/wiki/Zenk%C5%8D-ji",
  "Takayama Altstadt": "https://en.wikipedia.org/wiki/Takayama,_Gifu",
  "Shirakawa-go (Gassho-Zukuri)": "https://www.google.com/search?q=Shirakawa-go%20(Gassho-Zukuri)",
  "Kenrokuen-Garten": "https://de.wikipedia.org/wiki/Kenroku-en",
  "Burg Kanazawa": "https://de.wikipedia.org/wiki/Burg_Kanazawa",
  "Higashi Chaya-Gasse": "https://www.google.com/search?q=Higashi%20Chaya-Gasse",
  "Tateyama-Kurobe (Murodo)": "https://www.alpen-route.com/en/",
  "Kurobe-Staudamm": "https://en.wikipedia.org/wiki/Kurobe_Dam",
  "Nakasendo Magome": "https://en.wikipedia.org/wiki/Magome-juku",
  "Nakasendo Tsumago": "https://en.wikipedia.org/wiki/Tsumago-juku",
  "Izu Jogasaki-Küste": "https://www.google.com/search?q=Izu%20Jogasaki-K%C3%BCste",
  "Atami Onsen": "https://en.wikipedia.org/wiki/Atami,_Shizuoka",
  "Nagoya-jo (Burg)": "https://de.wikipedia.org/wiki/Burg_Nagoya",
  "Osu Shopping District": "https://en.wikipedia.org/wiki/%C5%8Csu",
  "Ghibli Park": "https://ghibli-park.jp/en/",
  "Ise-jingu": "https://de.wikipedia.org/wiki/Ise-jing%C5%ū",

  // Kansai
  "Fushimi Inari-taisha": "https://www.google.com/search?q=Fushimi%20Inari-taisha",
  "Kiyomizu-dera": "https://de.wikipedia.org/wiki/Kiyomizu-dera",
  "Kinkaku-ji (Goldener Pavillon)": "https://de.wikipedia.org/wiki/Kinkaku-ji",
  "Ginkaku-ji (Silberner Pavillon)": "https://de.wikipedia.org/wiki/Ginkaku-ji",
  "Arashiyama Bambuswald": "https://www.google.com/search?q=Arashiyama%20Bambuswald",
  "Nijo-jo (Burg Nijo)": "https://de.wikipedia.org/wiki/Burg_Nij%C5%8D",
  "Philosophenweg": "https://www.google.com/search?q=Philosophenweg",
  "Nishiki-Markt": "https://en.wikipedia.org/wiki/Nishiki_Market",
  "Nara-Park & Todai-ji": "https://de.wikipedia.org/wiki/T%C5%8Ddai-ji",
  "Kasuga Taisha": "https://de.wikipedia.org/wiki/Kasuga-Taisha",
  "Dotonbori": "https://www.google.com/search?q=Dotonbori",
  "Osaka-jo (Burg)": "https://de.wikipedia.org/wiki/Burg_%C5%8Csaka",
  "Umeda Sky Building": "https://www.google.com/search?q=Umeda%20Sky%20Building",
  "Shinsekai": "https://en.wikipedia.org/wiki/Shinsekai",
  "Kaiyukan Aquarium": "https://en.wikipedia.org/wiki/Osaka_Aquarium_Kaiyukan",
  "Universal Studios Japan": "https://www.usj.co.jp/web/en/us",
  "Himeji-jo (Burg Himeji)": "https://de.wikipedia.org/wiki/Burg_Himeji",
  "Koyasan & Okunoin": "https://en.wikipedia.org/wiki/Okunoin",
  "Kumano Nachi no Taki": "https://en.wikipedia.org/wiki/Nachi_Falls",
  "Kinosaki Onsen": "https://en.wikipedia.org/wiki/Kinosaki_Onsen",
  "Amanohashidate": "https://de.wikipedia.org/wiki/Amanohashidate",

  // Chugoku
  "Friedensdenkmal Hiroshima": "https://www.google.com/search?q=Friedensdenkmal%20Hiroshima",
  "Itsukushima-Schrein (Miyajima)": "https://de.wikipedia.org/wiki/Itsukushima-Schrein",
  "Korakuen-Garten": "https://www.google.com/search?q=Korakuen-Garten",
  "Burg Okayama": "https://de.wikipedia.org/wiki/Burg_Okayama",
  "Kurashiki Bikan Altstadt": "https://en.wikipedia.org/wiki/Kurashiki",
  "Tottori Sanddünen": "https://www.google.com/search?q=Tottori%20Sandd%C3%BCnen",
  "Izumo Taisha": "https://de.wikipedia.org/wiki/Izumo-Schrein",
  "Adachi Museum of Art": "https://www.adachi-museum.or.jp/en",
  "Kintaikyo-Brücke": "https://www.google.com/search?q=Kintaikyo-Br%C3%BCcke",
  "Sandankyo-Schlucht": "https://www.google.com/search?q=Sandankyo-Schlucht",

  // Shikoku
  "Ritsurin-Garten": "https://de.wikipedia.org/wiki/Ritsurin-Park",
  "Dogo Onsen": "https://de.wikipedia.org/wiki/D%C5%8Dgo_Onsen",
  "Matsuyama-jo (Burg)": "https://www.google.com/search?q=Matsuyama-jo%20(Burg)",
  "Iya-Tal & Rebenbrücken": "https://en.wikipedia.org/wiki/Iya_Valley",
  "Kochi-jo (Burg)": "https://de.wikipedia.org/wiki/Burg_K%C5%8Dchi",
  "Naruto-Strudel": "https://www.google.com/search?q=Naruto-Strudel",

  // Kyushu
  "Ohori-Park": "https://en.wikipedia.org/wiki/%C5%8Chori_Park",
  "Dazaifu Tenmangu": "https://de.wikipedia.org/wiki/Dazaifu_Tenmang%C5%ū",
  "Ainoshima (Katzeninsel)": "https://www.google.com/search?q=Ainoshima%20(Katzeninsel)",
  "Nagasaki Friedenspark": "https://de.wikipedia.org/wiki/Friedenspark_(Nagasaki)",
  "Glover Garden": "https://en.wikipedia.org/wiki/Glover_Garden",
  "Hashima (Gunkanjima)": "https://de.wikipedia.org/wiki/Hashima",
  "Kumamoto-jo (Burg)": "https://de.wikipedia.org/wiki/Burg_Kumamoto",
  "Suizenji Jojuen": "https://en.wikipedia.org/wiki/Suizen-ji_J%C5%8Dju-en",
  "Aso-Kaldera": "https://de.wikipedia.org/wiki/Aso_(Vulkan)",
  "Beppu Jigoku (Höllen)": "https://en.wikipedia.org/wiki/Beppu,_%C5%8Cita#Hot_springs",
  "Yufuin": "https://en.wikipedia.org/wiki/Yufuin",
  "Takachiho-Schlucht": "https://www.google.com/search?q=Takachiho-Schlucht",
  "Kagoshima & Sakurajima": "https://de.wikipedia.org/wiki/Sakurajima",
  "Yakushima": "https://de.wikipedia.org/wiki/Yakushima",

  // Okinawa
  "Shuri-jo (Schloss Shuri)": "https://de.wikipedia.org/wiki/Burg_Shuri",
  "Churaumi-Aquarium": "https://churaumi.okinawa/en/",
  "Cape Manzamo": "https://en.wikipedia.org/wiki/Manzamo",
  "Kouri-Brücke": "https://www.google.com/search?q=Kouri-Br%C3%BCcke",
  "Kerama-Inseln (Zamami)": "https://en.wikipedia.org/wiki/Kerama_Islands",
  "Miyakojima (Yonaha Maehama)": "https://www.google.com/search?q=Miyakojima%20(Yonaha%20Maehama)"
};
