// A curated selection of important attractions in Japan with matching emojis and coordinates
// Structure: { name, city, type, emoji, lat, lng, desc }
const attractions = [
  // Hokkaido
  { name: "Sapporo Snow Festival (Odori Park)", city: "Sapporo", type: "Festival", emoji: "❄️", lat: 43.0621, lng: 141.3544, desc: "Ice sculptures and winter atmosphere in the city center." },
  { name: "Otaru Canal", city: "Otaru", type: "Canal/District", emoji: "🚤", lat: 43.1976, lng: 140.9947, desc: "Historic canal with a romantic promenade." },
  { name: "Furano & Biei Flower Fields", city: "Furano/Biei", type: "Nature", emoji: "🌻", lat: 43.3423, lng: 142.3830, desc: "Vivid flower fields and gentle hills." },
  { name: "Daisetsuzan National Park", city: "Hokkaido", type: "National Park", emoji: "🏞️", lat: 43.6580, lng: 142.8540, desc: "Japan's largest national park, wild mountain landscapes." },
  { name: "Shiretoko Peninsula", city: "Shari", type: "UNESCO/National Park", emoji: "🏞️", lat: 44.1230, lng: 145.1250, desc: "Untouched nature, bears, and coastal cliffs." },
  { name: "Lake Akan & Ainu Kotan", city: "Kushiro", type: "Lake/Culture", emoji: "🛶", lat: 43.4480, lng: 144.1030, desc: "Clear crater lake and Ainu culture." },
  { name: "Noboribetsu Onsen (Jigokudani)", city: "Noboribetsu", type: "Onsen", emoji: "♨️", lat: 42.4920, lng: 141.1440, desc: "Steaming hell valley and hot springs." },
  { name: "Asahiyama Zoo", city: "Asahikawa", type: "Zoo", emoji: "🐧", lat: 43.7687, lng: 142.4823, desc: "Popular zoo with naturalistic enclosures." },
  { name: "Cape Kamui (Shakotan)", city: "Shakotan", type: "Cape/Coast", emoji: "🌊", lat: 43.3097, lng: 140.4852, desc: "Turquoise sea and dramatic cliffs." },

  // Tohoku
  { name: "Matsushima Bay", city: "Miyagi", type: "Bay", emoji: "🌊", lat: 38.3704, lng: 141.0614, desc: "One of Japan's three most scenic views." },
  { name: "Hirosaki Castle & Park", city: "Hirosaki", type: "Castle/Cherry Blossom", emoji: "🏯", lat: 40.6065, lng: 140.4635, desc: "Cherry blossoms in front of a historic castle." },
  { name: "Lake Towada", city: "Aomori/Akita", type: "Lake", emoji: "🏞️", lat: 40.4500, lng: 140.8940, desc: "Deep crater lake in a forested setting." },
  { name: "Oirase Gorge", city: "Aomori", type: "Gorge", emoji: "🏞️", lat: 40.4860, lng: 140.9500, desc: "Mossy banks, clear streams, and waterfalls." },
  { name: "Yamadera (Risshaku-ji)", city: "Yamagata", type: "Temple", emoji: "🛕", lat: 38.3103, lng: 140.4322, desc: "Mountain temple with 1000 steps and panoramic views." },
  { name: "Ginzan Onsen", city: "Obanazawa", type: "Onsen", emoji: "♨️", lat: 38.5580, lng: 140.5140, desc: "Taisho-era romance and gas-lit alleys." },
  { name: "Zao Onsen & Snow Monsters", city: "Yamagata", type: "Onsen/Winter", emoji: "♨️", lat: 38.1700, lng: 140.4100, desc: "Ski resort with bizarre ice-covered trees." },
  { name: "Lake Tazawa", city: "Semboku", type: "Lake", emoji: "🏞️", lat: 39.7310, lng: 140.7300, desc: "Japan's deepest lake with turquoise water." },
  { name: "Kakunodate Samurai District", city: "Semboku", type: "Old Town", emoji: "🏘️", lat: 39.5930, lng: 140.5640, desc: "Well-preserved samurai residences." },
  { name: "Aizu-Wakamatsu (Tsuruga Castle)", city: "Fukushima", type: "Castle", emoji: "🏯", lat: 37.4940, lng: 139.9290, desc: "White castle with Boshin War history." },
  { name: "Sendai Zuihoden", city: "Sendai", type: "Mausoleum", emoji: "🏛️", lat: 38.2460, lng: 140.8660, desc: "Magnificent mausoleum of Date Masamune." },
  { name: "Aomori Nebuta Museum WA-RASSE", city: "Aomori", type: "Festival/Museum", emoji: "🎆", lat: 40.8280, lng: 140.7340, desc: "Glowing festival floats of Nebuta Matsuri." },
  { name: "Tashirojima (Cat Island)", city: "Ishinomaki (Miyagi)", type: "Island/Cats", emoji: "🐈", lat: 38.2969, lng: 141.3919, desc: "Small island with free-roaming cats; ferry from Ishinomaki." },

  // Kanto (Tokyo & surroundings)
  { name: "Senso-ji (Asakusa)", city: "Tokyo", type: "Temple", emoji: "🛕", lat: 35.7148, lng: 139.7967, desc: "Tokyo's oldest temple with Kaminari-mon." },
  { name: "Meiji Jingu", city: "Tokyo", type: "Shrine", emoji: "⛩️", lat: 35.6764, lng: 139.6993, desc: "Forest shrine near Harajuku/Shibuya." },
  { name: "Shibuya Crossing", city: "Tokyo", type: "Crossing", emoji: "🚦", lat: 35.6595, lng: 139.7005, desc: "Legendary crossing with crowds of people." },
  { name: "Tokyo Skytree", city: "Tokyo", type: "Tower", emoji: "🗼", lat: 35.7101, lng: 139.8107, desc: "Observation and TV tower with Solamachi." },
  { name: "Tokyo Tower", city: "Tokyo", type: "Tower", emoji: "🗼", lat: 35.6586, lng: 139.7454, desc: "Icon in the heart of Tokyo." },
  { name: "Akihabara", city: "Tokyo", type: "Electronics/Pop Culture", emoji: "🎮", lat: 35.6984, lng: 139.7730, desc: "Otaku, games, and electronics mecca." },
  { name: "teamLab Planets", city: "Tokyo (Toyosu)", type: "Museum", emoji: "🏛️", lat: 35.6457, lng: 139.7969, desc: "Immersive light and water installations." },
  { name: "Ueno Park & Museums", city: "Tokyo", type: "Park/Museums", emoji: "🌳", lat: 35.7156, lng: 139.7730, desc: "Large park with zoo and top museums." },
  { name: "Shinjuku Gyoen", city: "Tokyo", type: "Garden/Park", emoji: "🌳", lat: 35.6852, lng: 139.7100, desc: "Oasis with Japanese, English, and French gardens." },
  { name: "Tsukiji Outer Market", city: "Tokyo", type: "Market/Food", emoji: "🍣", lat: 35.6655, lng: 139.7700, desc: "Street food and fresh seafood." },
  { name: "Ghibli Museum", city: "Mitaka (Tokyo)", type: "Museum", emoji: "🏛️", lat: 35.7023, lng: 139.5703, desc: "Enchanting museum for Studio Ghibli." },
  { name: "Yokohama Minato Mirai", city: "Yokohama", type: "Cityscape", emoji: "🌆", lat: 35.4570, lng: 139.6380, desc: "Waterfront promenade with Landmark Tower." },
  { name: "Yokohama Chinatown", city: "Yokohama", type: "District/Food", emoji: "🍜", lat: 35.4420, lng: 139.6500, desc: "Japan's largest Chinatown." },
  { name: "Cup Noodles Museum", city: "Yokohama", type: "Museum", emoji: "🏛️", lat: 35.4550, lng: 139.6380, desc: "Instant noodle history to experience." },
  { name: "Great Buddha of Kamakura", city: "Kamakura", type: "Temple/Buddha", emoji: "🛕", lat: 35.3167, lng: 139.5350, desc: "Daibutsu at Kotoku-in." },
  { name: "Tsurugaoka Hachimangu", city: "Kamakura", type: "Shrine", emoji: "⛩️", lat: 35.3260, lng: 139.5540, desc: "Kamakura's most important shrine." },
  { name: "Enoshima", city: "Fujisawa", type: "Island/Beach", emoji: "🏝️", lat: 35.3000, lng: 139.4800, desc: "Leisure island with lighthouse and beaches." },
  { name: "Nikko Toshogu", city: "Nikko", type: "Shrine", emoji: "⛩️", lat: 36.7570, lng: 139.5993, desc: "Magnificently decorated shrine (UNESCO)." },
  { name: "Kegon Waterfall", city: "Nikko", type: "Waterfall", emoji: "💧", lat: 36.7350, lng: 139.4930, desc: "Spectacular fall at Lake Chuzenji." },
  { name: "Lake Chuzenji", city: "Nikko", type: "Lake", emoji: "🏞️", lat: 36.7450, lng: 139.5110, desc: "High-altitude lake west of Nikko." },
  { name: "Hakone Lake Ashi", city: "Hakone", type: "Lake", emoji: "🏞️", lat: 35.2040, lng: 139.0240, desc: "Postcard view with torii and Fuji." },
  { name: "Owakudani", city: "Hakone", type: "Volcanic Landscape", emoji: "🌋", lat: 35.2420, lng: 139.0190, desc: "Sulfur fumes, black eggs, and views." },
  { name: "Hakone Open-Air Museum", city: "Hakone", type: "Museum", emoji: "🏛️", lat: 35.2560, lng: 139.1040, desc: "Sculpture park in the mountains." },
  { name: "Kawagoe (Little Edo)", city: "Kawagoe", type: "Old Town", emoji: "🏘️", lat: 35.9250, lng: 139.4850, desc: "Bell tower Toki no Kane and old town alleys." },
  { name: "Chureito Pagoda (Arakura Sengen)", city: "Fujiyoshida", type: "Shrine/Pagoda", emoji: "⛩️", lat: 35.4930, lng: 138.8090, desc: "Fuji view with red pagoda (sakura)." },

  // Chubu (Central Japan)
  { name: "Fuji-san (Mount Fuji)", city: "Shizuoka/Yamanashi", type: "Mountain", emoji: "🗻", lat: 35.3606, lng: 138.7274, desc: "Iconic volcano and UNESCO World Heritage." },
  { name: "Jigokudani Snow Monkey Park", city: "Yamanouchi", type: "Animals/Onsen", emoji: "🐒", lat: 36.7320, lng: 138.4620, desc: "Bathing macaques in winter steam." },
  { name: "Matsumoto Castle", city: "Matsumoto", type: "Castle", emoji: "🏯", lat: 36.2380, lng: 137.9690, desc: "Black castle, also called 'Crow Castle'." },
  { name: "Zenko-ji", city: "Nagano", type: "Temple", emoji: "🛕", lat: 36.6610, lng: 138.1870, desc: "One of the oldest temples in Japan." },
  { name: "Takayama Old Town", city: "Takayama", type: "Old Town", emoji: "🏘️", lat: 36.1400, lng: 137.2560, desc: "Sake breweries and traditional houses." },
  { name: "Shirakawa-go (Gassho-Zukuri)", city: "Gifu", type: "UNESCO/Village", emoji: "🏘️", lat: 36.2600, lng: 136.8980, desc: "Thatched-roof farmhouses in mountain valleys." },
  { name: "Kenrokuen Garden", city: "Kanazawa", type: "Garden", emoji: "🏛️", lat: 36.5610, lng: 136.6620, desc: "One of Japan's three famous gardens." },
  { name: "Kanazawa Castle", city: "Kanazawa", type: "Castle", emoji: "🏯", lat: 36.5660, lng: 136.6590, desc: "Extensive castle grounds by Kenrokuen." },
  { name: "Higashi Chaya District", city: "Kanazawa", type: "Old Town", emoji: "🏘️", lat: 36.5730, lng: 136.6730, desc: "Teahouses and Geisha tradition." },
  { name: "Tateyama-Kurobe (Murodo)", city: "Toyama", type: "Mountain Route", emoji: "🏞️", lat: 36.5750, lng: 137.6030, desc: "Snow corridor and alpine panoramas." },
  { name: "Kurobe Dam", city: "Toyama", type: "Dam", emoji: "🏞️", lat: 36.5600, lng: 137.6690, desc: "Impressive arch dam in the Alps." },
  { name: "Nakasendo Magome", city: "Gifu", type: "Hiking Trail", emoji: "🥾", lat: 35.5160, lng: 137.6070, desc: "Post station on the historic Nakasendo." },
  { name: "Nakasendo Tsumago", city: "Nagano", type: "Hiking Trail", emoji: "🥾", lat: 35.4650, lng: 137.5970, desc: "Authentic Edo-period post town." },
  { name: "Izu Jogasaki Coast", city: "Ito (Shizuoka)", type: "Coast", emoji: "🌊", lat: 34.8770, lng: 139.1100, desc: "Cliffside trails, suspension bridge, and surf." },
  { name: "Atami Onsen", city: "Atami", type: "Onsen", emoji: "♨️", lat: 35.0960, lng: 139.0770, desc: "Coastal onsen near Tokyo." },
  { name: "Nagoya Castle", city: "Nagoya", type: "Castle", emoji: "🏯", lat: 35.1850, lng: 136.8990, desc: "Famous for its golden shachihoko." },
  { name: "Osu Shopping District", city: "Nagoya", type: "District/Food", emoji: "🍜", lat: 35.1580, lng: 136.9060, desc: "Street food, temples, and secondhand shops." },
  { name: "Ghibli Park", city: "Nagakute (Aichi)", type: "Theme Park", emoji: "🎢", lat: 35.1730, lng: 137.1240, desc: "Themed areas around Studio Ghibli." },
  { name: "Ise Jingu", city: "Ise (Mie)", type: "Shrine", emoji: "⛩️", lat: 34.4550, lng: 136.7250, desc: "Holiest shrine of Shinto." },

  // Kansai
  { name: "Fushimi Inari Taisha", city: "Kyoto", type: "Shrine", emoji: "⛩️", lat: 34.9671, lng: 135.7727, desc: "Thousands of red torii gates on the mountainside." },
  { name: "Kiyomizu-dera", city: "Kyoto", type: "Temple", emoji: "🛕", lat: 34.9949, lng: 135.7850, desc: "Wooden temple with a stage." },
  { name: "Kinkaku-ji (Golden Pavilion)", city: "Kyoto", type: "Temple", emoji: "🛕", lat: 35.0394, lng: 135.7292, desc: "Pavilion covered in gold leaf by the pond." },
  { name: "Ginkaku-ji (Silver Pavilion)", city: "Kyoto", type: "Temple", emoji: "🛕", lat: 35.0270, lng: 135.7986, desc: "Zen temple with a rock garden." },
  { name: "Arashiyama Bamboo Grove", city: "Kyoto", type: "Nature", emoji: "🎋", lat: 35.0094, lng: 135.6668, desc: "Atmospheric bamboo forest." },
  { name: "Nijo-jo (Nijo Castle)", city: "Kyoto", type: "Castle", emoji: "🏯", lat: 35.0140, lng: 135.7480, desc: "Shogun residence with nightingale floors." },
  { name: "Philosopher's Path", city: "Kyoto", type: "Walking Path", emoji: "🌸", lat: 35.0260, lng: 135.7980, desc: "Cherry blossom path along a canal." },
  { name: "Nishiki Market", city: "Kyoto", type: "Market/Food", emoji: "🍜", lat: 35.0050, lng: 135.7640, desc: "Kyoto's cuisine under one roof." },
  { name: "Nara Park & Todai-ji", city: "Nara", type: "Park/Temple", emoji: "🦌", lat: 34.6851, lng: 135.8431, desc: "Free-roaming deer and great Buddha hall." },
  { name: "Kasuga Taisha", city: "Nara", type: "Shrine", emoji: "⛩️", lat: 34.6810, lng: 135.8480, desc: "Stone and bronze lanterns in the forest." },
  { name: "Dotonbori", city: "Osaka", type: "District/Food", emoji: "🍜", lat: 34.6687, lng: 135.5011, desc: "Neon lights, street food, and Glico Man." },
  { name: "Osaka-jo (Osaka Castle)", city: "Osaka", type: "Castle", emoji: "🏯", lat: 34.6873, lng: 135.5262, desc: "Castle park and museum." },
  { name: "Umeda Sky Building", city: "Osaka", type: "Observation", emoji: "🌆", lat: 34.7055, lng: 135.4892, desc: "Floating garden observatory." },
  { name: "Shinsekai", city: "Osaka", type: "District", emoji: "🌃", lat: 34.6525, lng: 135.5063, desc: "Retro charm around Tsutenkaku." },
  { name: "Kaiyukan Aquarium", city: "Osaka", type: "Aquarium", emoji: "🐠", lat: 34.6545, lng: 135.4283, desc: "One of the largest aquariums in the world." },
  { name: "Universal Studios Japan", city: "Osaka", type: "Theme Park", emoji: "🎢", lat: 34.6654, lng: 135.4323, desc: "Themed worlds from Nintendo to Harry Potter." },
  { name: "Himeji-jo (Himeji Castle)", city: "Himeji", type: "Castle", emoji: "🏯", lat: 34.8394, lng: 134.6939, desc: "Magnificent white castle (UNESCO)." },
  { name: "Koyasan & Okunoin", city: "Wakayama", type: "Temple/Cemetery", emoji: "🛕", lat: 34.2128, lng: 135.5860, desc: "Spiritual center of Shingon Buddhism." },
  { name: "Kumano Nachi no Taki", city: "Nachikatsuura", type: "Waterfall", emoji: "💧", lat: 33.6670, lng: 135.8890, desc: "Tall waterfall next to a shrine." },
  { name: "Kinosaki Onsen", city: "Toyooka", type: "Onsen", emoji: "♨️", lat: 35.6260, lng: 134.8130, desc: "Bathing pass through seven bathhouses." },
  { name: "Amanohashidate", city: "Miyazu", type: "Sandbar/Panorama", emoji: "🌊", lat: 35.5660, lng: 135.1950, desc: "Heavenly path over the bay." },

  // Chugoku
  { name: "Hiroshima Peace Memorial", city: "Hiroshima", type: "Memorial", emoji: "🕊️", lat: 34.3955, lng: 132.4536, desc: "Memorial and museum." },
  { name: "Itsukushima Shrine (Miyajima)", city: "Hatsukaichi", type: "Shrine", emoji: "⛩️", lat: 34.2956, lng: 132.3199, desc: "Floating torii gate in the sea." },
  { name: "Korakuen Garden", city: "Okayama", type: "Garden", emoji: "🏛️", lat: 34.6693, lng: 133.9344, desc: "Spacious daimyo garden." },
  { name: "Okayama Castle", city: "Okayama", type: "Castle", emoji: "🏯", lat: 34.6654, lng: 133.9350, desc: "Black castle by the Asahi River." },
  { name: "Kurashiki Bikan Historical Quarter", city: "Kurashiki", type: "Old Town", emoji: "🏘️", lat: 34.5958, lng: 133.7718, desc: "White-walled storehouses along the canal." },
  { name: "Tottori Sand Dunes", city: "Tottori", type: "Dunes", emoji: "🏜️", lat: 35.5403, lng: 134.2383, desc: "Desert-like landscape by the sea." },
  { name: "Izumo Taisha", city: "Izumo", type: "Shrine", emoji: "⛩️", lat: 35.4010, lng: 132.6853, desc: "One of the oldest shrines in Japan." },
  { name: "Adachi Museum of Art", city: "Yasugi", type: "Museum/Garden", emoji: "🏛️", lat: 35.4314, lng: 133.2508, desc: "Famous museum garden." },
  { name: "Kintaikyo Bridge", city: "Iwakuni", type: "Bridge", emoji: "🌉", lat: 34.1667, lng: 132.1789, desc: "Five-arched wooden bridge over the Nishiki River." },
  { name: "Sandankyo Gorge", city: "Hiroshima", type: "Gorge", emoji: "🏞️", lat: 34.5670, lng: 132.2530, desc: "Boat tours and waterfalls in a narrow gorge." },

  // Shikoku
  { name: "Ritsurin Garden", city: "Takamatsu", type: "Garden", emoji: "🏛️", lat: 34.3302, lng: 134.0434, desc: "Spacious garden with ponds and hills." },
  { name: "Dogo Onsen", city: "Matsuyama", type: "Onsen", emoji: "♨️", lat: 33.8502, lng: 132.7799, desc: "One of the oldest bathhouses in Japan." },
  { name: "Matsuyama-jo (Castle)", city: "Matsuyama", type: "Castle", emoji: "🏯", lat: 33.8456, lng: 132.7656, desc: "Castle on a hill with views over the city." },
  { name: "Iya Valley & Vine Bridges", city: "Miyoshi", type: "Valley/Bridge", emoji: "🌉", lat: 33.9030, lng: 133.8140, desc: "Remote gorges and historic suspension bridges." },
  { name: "Kochi-jo (Castle)", city: "Kochi", type: "Castle", emoji: "🏯", lat: 33.5597, lng: 133.5311, desc: "One of the few original castles in Japan." },
  { name: "Naruto Whirlpools", city: "Naruto", type: "Sea Whirlpools", emoji: "🌊", lat: 34.1708, lng: 134.6412, desc: "Spectacular tidal whirlpools in the strait." },
  { name: "Shikoku 88 Temple Pilgrimage (Ryozenji)", city: "Tokushima", type: "Pilgrimage", emoji: "🥾", lat: 34.1308, lng: 134.5119, desc: "Starting temple of the Henro pilgrimage." },
  { name: "Aoshima (Cat Island)", city: "Ozu (Ehime)", type: "Island/Cats", emoji: "🐈", lat: 33.7360, lng: 132.4820, desc: "Famous cat island in the Seto Inland Sea." },

  // Kyushu
  { name: "Ohori Park", city: "Fukuoka", type: "Park", emoji: "🌳", lat: 33.5869, lng: 130.3763, desc: "Central lake park with running paths." },
  { name: "Dazaifu Tenmangu", city: "Dazaifu", type: "Shrine", emoji: "⛩️", lat: 33.5222, lng: 130.5341, desc: "Education shrine with plum blossoms." },
  { name: "Ainoshima (Cat Island)", city: "Shingu (Fukuoka)", type: "Island/Cats", emoji: "🐈", lat: 33.7440, lng: 130.3220, desc: "Cat-rich island near Fukuoka; ferry from Shingu." },
  { name: "Nagasaki Peace Park", city: "Nagasaki", type: "Memorial", emoji: "🕊️", lat: 32.7766, lng: 129.8647, desc: "Memorial park near the hypocenter." },
  { name: "Glover Garden", city: "Nagasaki", type: "Garden", emoji: "🏛️", lat: 32.7357, lng: 129.8694, desc: "Historic western residences." },
  { name: "Hashima (Gunkanjima)", city: "Nagasaki", type: "Island/Industry", emoji: "🏝️", lat: 32.6278, lng: 129.7386, desc: "Abandoned coal island, boat tours from Nagasaki." },
  { name: "Kumamoto-jo (Castle)", city: "Kumamoto", type: "Castle", emoji: "🏯", lat: 32.8031, lng: 130.7079, desc: "Mighty castle, partly restored." },
  { name: "Suizenji Jojuen", city: "Kumamoto", type: "Garden", emoji: "🏛️", lat: 32.7878, lng: 130.7412, desc: "Miniature landscapes and tea houses." },
  { name: "Aso Caldera", city: "Aso", type: "Volcano", emoji: "🌋", lat: 32.8840, lng: 131.1040, desc: "One of the largest volcanic calderas in the world." },
  { name: "Beppu Jigoku (Hells)", city: "Beppu", type: "Onsen", emoji: "♨️", lat: 33.3074, lng: 131.4915, desc: "Colorful hot springs and foot baths." },
  { name: "Yufuin", city: "Yufu", type: "Onsen", emoji: "♨️", lat: 33.2617, lng: 131.3195, desc: "Cozy spa town with art and nature." },
  { name: "Takachiho Gorge", city: "Miyazaki", type: "Gorge", emoji: "🏞️", lat: 32.7036, lng: 131.3086, desc: "Basalt gorge with boats and waterfalls." },
  { name: "Kagoshima & Sakurajima", city: "Kagoshima", type: "Volcano", emoji: "🌋", lat: 31.5934, lng: 130.6628, desc: "Active volcano in Kagoshima Bay." },
  { name: "Yakushima", city: "Yakushima", type: "UNESCO/Nature", emoji: "🌳", lat: 30.3580, lng: 130.5280, desc: "Primeval cedar forests and mossy paths." },

  // Okinawa
  { name: "Shuri-jo (Shuri Castle)", city: "Naha", type: "Castle", emoji: "🏯", lat: 26.2174, lng: 127.7195, desc: "Reconstructed Ryukyu palace complex." },
  { name: "Churaumi Aquarium", city: "Motobu", type: "Aquarium", emoji: "🐠", lat: 26.6942, lng: 127.8779, desc: "Whale sharks and giant tanks." },
  { name: "Cape Manzamo", city: "Onna", type: "Cape/Coast", emoji: "🌊", lat: 26.5027, lng: 127.8522, desc: "Elephant trunk cliff over turquoise sea." },
  { name: "Kouri Bridge", city: "Nakijin", type: "Bridge", emoji: "🌉", lat: 26.7108, lng: 127.9640, desc: "Long sea bridge with dreamlike colors." },
  { name: "Kerama Islands (Zamami)", city: "Zamami", type: "Island/Sea", emoji: "🏝️", lat: 26.2300, lng: 127.3040, desc: "Snorkeling paradise near Naha." },
  { name: "Miyakojima (Yonaha Maehama)", city: "Miyako", type: "Beach", emoji: "🏖️", lat: 24.7370, lng: 125.3110, desc: "Powdery beach and turquoise water." },
  { name: "Kabira Bay (Ishigaki)", city: "Ishigaki", type: "Bay", emoji: "🌊", lat: 24.4723, lng: 124.1359, desc: "Postcard bay with emerald green water." },
  { name: "Iriomote (Mangroves & Waterfalls)", city: "Iriomote", type: "Nature", emoji: "🛶", lat: 24.3500, lng: 123.8830, desc: "Jungle, mangroves, and river adventures." }
];
